CREATE DATABASE IF NOT EXISTS ZKRcompany
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE ZKRcompany;

CREATE TABLE IF NOT EXISTS contacts (

    id INT AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(150) NOT NULL,

    subject VARCHAR(255) NOT NULL,

    message TEXT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS admin (

    id INT AUTO_INCREMENT PRIMARY KEY,

    username VARCHAR(100) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

INSERT INTO admin
(
    username,
    password
)
VALUES
(
    'admin',
    '$2y$10$wH5aK2JzZ7M2YkP4nJjM6e5YkRjK7hM7L4O0z6M1Xk6gM9iP4t7Da'
);